timeout_min: 720 # [1day=1440, 2day=2880, 5day=7200]
nodes: 1
tasks_per_node: 4
gpus_per_task: 1
cpus_per_gpu: 12
mem_per_cpu: 3

# default value
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
gpus_per_node: null
mem_gb: null
cpus_per_task: null


name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: allgpu, classicgpu
qos: null
comment: null
constraint: null
exclude: null
gres: null
mem_per_gpu: null
account: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null
srun_args: null