name: image_custom

defaults:
  - data: CIFAR10
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
  - _self_

data:
  partition: random

model: custom_McMahan_32_32

# Server and user:
num_queries: 1

# User data:
user:
  provide_labels: True
  num_data_points: 4
